### ISSUE TITLE
Submitting in distributed storm cluster- Netty reconnect issue

### ISSUE THREAD

**Issue by siddharthU** [HolmesNL/kafka-spout#14]
Hi, i am trying to submit a topology based on your project . I seem to do fine in localcluster however, in the distributed mode the workers are not starting and i am getting an error "Netty reconnect workername" over n over again. can you pls help?

**Comment by akaIDIOT** [comment]
This sounds like a problem not related to the spout itself; are you sure all workers are able to connect to the nimbus and you're able to run other topologies in distributed mode?

**Comment by siddharthU** [comment]
hi,
The problem seems to be with supervisor where it says unable to start the supervisor.
its not getting up with the following jmessage is supervisor logs 
"2015-01-20T19:53:13.764+0530 b.s.d.supervisor [INFO] 6f4438a6-5fd1-4a7d-805a-f59339e77a9f still hasn't started
2015-01-20T19:53:14.265+0530 b.s.d.supervisor [INFO] 6f4438a6-5fd1-4a7d-805a-f59339e77a9f still hasn't started
2015-01-20T19:53:14.766+0530 b.s.d.supervisor [INFO] 6f4438a6-5fd1-4a7d-805a-f59339e77a9f still hasn't started
2015-01-20T19:53:15.266+0530 b.s.d.supervisor [INFO] 6f4438a6-5fd1-4a7d-805a-f59339e77a9f still hasn't started
2015-01-20T19:53:15.767+0530 b.s.d.supervisor [INFO] 6f4438a6-5fd1-4a7d-805a-f59339e77a9f still hasn't started
2015-01-20T19:53:16.268+0530 b.s.d.supervisor [INFO] 6f4438a6-5fd1-4a7d-805a-f59339e77a9f still hasn't started"

**Comment by akaIDIOT** [comment]
Just saw your post on the mailing list. Please be aware that the kafk/storm integration you're referring to in your post (judging by the code you posted) is *not* from this project. 

'This' kafka spout is an alternative to the one available from the storm team and uses a different client approach. Is your problem related to this project or the one from the storm team?

Unless of course the post on the mailing list is from someone else, in which case feel free to ignore this reply :).

**Comment by siddharthU** [comment]
hi,

I have tried both approaches . Your project as well as the storm project on github.
Seems like problem is about the worker & supervisor not starting. I posted this query in the first place when i was usnig ur project. However, with the other project also i am getting similar resulkts.
Any idea why the worker& supervisor wont start?

**Comment by akaIDIOT** [comment]
Not without details of your setup, sorry. For issues regarding storm itself, the mailing list is a better bet; lots more people there who might recognize your problem...
