### ISSUE TITLE
we have setup all the tunning params for kafka and strom still getting very high latency

### ISSUE THREAD

**Issue by imvipul** [HolmesNL/kafka-spout#17]
we have 3 node kafka cluster....3 node zookeeper and 1 node storm cluster with 8 CPU per node....there is enough memory and disk space available...we are using kafkaspout ...for testing we have a topology with two spout reading message from two topics and sending it to bolt which is outputting it to kafka topic....we are facing very high latency

**Comment by errordaiwa** [comment]
Put this

    config.put("kafka.consumer.timeout.ms", 50);
    config.put("kafka.spout.buffer.size.max", 1);
in your topology config and retry ^_^. We fixed our latency issue by modify this config.

**Comment by akaIDIOT** [comment]
Sorry for the delay, guys. The two config options @errordaiwa mentions are exactly the two parameters at play here. Setting the buffer size to 1 will flush every message separately, but create some overhead for each tuple. The consumer timeout setting controls the max time to wait for more tuples.

Depending on the throughput of the kafka topic you're reading from and the latency between the kafka broker and client, I'd recommend setting the timeout just above the 'natural' latency between the two for minimal latency in your topology. A small buffer size (like 1, or 10, or whatever is small for your use case) will ensure the spout won't wait around too long before emitting the buffered tuples into your topology.

Hope this helps :)
