### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by gagle** [HolmesNL/kafka-spout#18]
Can you update the maven repository with the latest source code?

**Comment by akaIDIOT** [comment]
Whoops, sorry for the rather late reply here. Updating maven central is a great idea, really, I'll go bug a colleague for the key to sign bundle, stay tuned ;)

**Comment by gagle** [comment]
Any news on that?

**Comment by akaIDIOT** [comment]
Managed to dig up the key and release state of development branch to maven central as version 0.3. Should be synced to central any moment now.
Terribly sorry for the delay, very busy times here :)
